name       : python-sdl2
version    : 0.9.15
release    : 11
source     :
    - https://github.com/marcusva/py-sdl2/archive/refs/tags/0.9.15.tar.gz : 144d92a948bf36e12ed9fb31f80055b0eaf049b0f7fe0c5d9a495c85cd5f4ddd
license    :
    - Public-Domain
    - Python-2.0
component  : programming.python
summary    : PySDL2 is a wrapper around the SDL2 library.
description: |
    PySDL2 is a wrapper around the SDL2 library and as such similar to the discontinued PySDL project. In contrast to PySDL, it has no licensing restrictions, nor does it rely on C code, but uses ctypes instead.
rundeps    :
    - sdl2
build      : |
    %python3_setup
install    : |
    %python3_install
