name       : python-sdl2
version    : 0.9.6
release    : 5
source     :
    - https://github.com/marcusva/py-sdl2/archive/rel_0_9_6.tar.gz : 50e137cc6078d20d59c7a79883a684a02cbeaa583c9f43ac6bfbcca364236f97
license    :
    - Public-Domain
    - Python-2.0
component  : programming.python
summary    : PySDL2 is a wrapper around the SDL2 library.
description: |
    PySDL2 is a wrapper around the SDL2 library and as such similar to the discontinued PySDL project. In contrast to PySDL, it has no licensing restrictions, nor does it rely on C code, but uses ctypes instead.
rundeps    :
    - sdl2
build      : |
    %python3_setup
install    : |
    %python3_install
